package com.example.clinton.companion.utilities;


public enum FRAGMENT_ID {
    LIFESTYLE_ID,
    SCIENCE_ID,
    SPORT_ID,
    CULTURE_ID,
    WORLD_ID,
    MAIN_DICTIONARY_ID,
    RANDOM_WORD_ID,
    RELATED_ID,
    MAIN_ACTIVITY_ID,
    NEWS_SEARCH_FRAGMENT_ID,
    NEWS_FAVORITE_FRAG_ID,
    DICTIONARY_FAVORITE_ID,
    DICTIONARY_RECENT_ID,
    NEWS_HOME_LIFE,
    NEWS_HOME_SCIENCE,
    NEWS_HOME_SPORT,
    NEWS_HOME_CULTURE,
    NEWS_HOME_WORLD,
    DICTIONARY_HOME,
    SEARCH_HOME,
    TODAY_HOME,
    RANDOM_HOME,
    QUOTE_ID
}
